version: '3.8'

services:
  api:
    build:
      context: ./ApiExtension
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
    depends_on:
      - ollama
    networks:
      - ai-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - '11434:11434'
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - ai-network

networks:
  ai-network:
    driver: bridge

volumes:
  ollama_data:
